In [4]:
import numpy as np
#create matrix
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
#addition
C=A+B
#SUBSTRACTION
D=A-B
#MATRIX MULTIPLICATION(ELEMENY WISE)
E=A*B
#MATRIX MULTIPLICATION
F=np.dot(A,B)
#A@B
#TRANSPOSE
A_transpose=A.T
print("Addition:")
print(C)
print("\nSubstraction:")
print(D)
print("\n Element wise multiplication:")
print(E)
print("\n Matrix multiplication:")
print(F)
print("\nTranspose:")
print(A_transpose)

Addition:
[[ 6  8]
 [10 12]]

Substraction:
[[-4 -4]
 [-4 -4]]

 Element wise multiplication:
[[ 5 12]
 [21 32]]

 Matrix multiplication:
[[19 22]
 [43 50]]

Transpose:
[[1 3]
 [2 4]]
